/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package addressbook4;

import org.junit.Test;
import static org.junit.Assert.*;

public class AddressBookTest {
	@Test
	public void givenDatabase_WhenDataRetrieved_ShouldPassTest() {
		assertEquals("Lionel", new AddressBookDBIOService().retrieveData().get(5).firstName);
	}
	
	@Test
	public void givenDatabase_WhenDataUpdated_ShouldPassTest() {
		assertEquals(1, new AddressBookDBIOService().updateData("Preetam", "123456"));
	}
	
	
}
